### ISSUE TITLE
Slow startup for terminals

### ISSUE THREAD

**Issue by mattmusc** [dylanaraps/wal#7] opened 2017-01-19 09:39 UTC
Hi,

I am experiencing slow shell startup after putting `wal -r` in my `.bashrc`.
I am using `Arch Linux 4.8.13-1` and `bash 4.4.5`

These are the timings:
```
[musci@archiematti ~]$ time source .bashrc

real	0m0.047s
**user	0m0.030s**
sys	0m0.010s
[musci@archiematti ~]$ 
```

Enabling debug mode in bash with `set +x` shows that what's slowing down is exactly wal.

Could I somehow load the color scheme generated once from cache and not having to execute `wal -r` for each terminal?

Also, as a side note, `wal -i "$(< "${HOME}/.cache/wal/wal")"` in this code I can't understand where is the `wal` file, because in my `${HOME}/.cache/wal/` there are these folders and files:

```
[musci@archiematti ~]$ ls .cache/wal/
colors  colors.scss  colors.sh  schemes
[musci@archiematti ~]$ ls .cache/wal/schemes
-home-musci-pic-0321.jpg
```

In the paragraph [here](https://github.com/dylanaraps/wal#making-the-colorscheme-persist-on-reboot) were you referring to this `-home-musci-pic-0321.jpg` file?

Thanks for the useful tool

matteo

**Comment by dylanaraps** [comment] 2017-01-19 09:57
Hiya,

> Could I somehow load the color scheme generated once from cache and not having to execute wal -r for each terminal?

`wal -r` is required because `wal` doesn't modify any terminal config files (nor should it). Basically as far as your terminal is aware, it's using its regular colors defined in its config file. 

I'll look into the slow startup issues and possibly optimize `wal -r` so it does the bare minimum. 

As a reference, here's the startup time of `bash` + `wal` on my system:

```sh
dylan ~ >time source .bashrc

real	0m0.018s
user	0m0.010s
sys	0m0.000s

dylan ~ >time wal -r

real	0m0.011s
user	0m0.007s
sys	0m0.000s
```

> Also, as a side note, wal -i "$(< "${HOME}/.cache/wal/wal")" in this code I can't understand where is the wal file, because in my ${HOME}/.cache/wal/ there are these folders and files:

I'm not sure about why there's no `wal` file in the directory on your system. The `wal` file just contains the path to the wallpaper that is currently set. Here's what it looks like on mine:

```sh
dylan ~ >ls .cache/wal
colors	colors.rofi  colors.scss  colors.sh  schemes  wal
```

I'll look into both of these issues, thanks for reporting them. :)

**Comment by dylanaraps** [comment] 2017-01-19 09:59
One more thing:

- What terminal emulator are you using?

**Comment by dylanaraps** [comment] 2017-01-19 10:12
I don't think any further optimization can be done to `wal -r`. All the `-r` flag does is read the saved color-scheme from a file (`${HOME}.cache/wal/colors`) and print the contents of the file to the terminal.

I just did some digging and we can remove all of the startup delay from `wal -r` by running it in the background. This way the colorscheme is still applied to the current terminal and it doesn't delay `bash`'s startup.

Just change the `wal -r` command to the following:

```sh
(wal -r &)

# Here's how it works:
&   # Run the process in the background.
( ) # Hide bash job control messages.
```

I'm going to update the README to include this as I think it'll benefit everyone using `wal`.

**Comment by mattmusc** [comment] 2017-01-19 10:16
Thanks, I was trying to run it in the background as well, but didn't know about `( )` :)

I am using `urxvt v9.22`

**Comment by dylanaraps** [comment] 2017-01-19 10:21
After successfully running `wal -i path/to/img.jpg` (successful meaning schemes + wallpaper were changed), can you check the contents of the `.cache/wal/` directory? Is there a `wal` file there now?

**Comment by mattmusc** [comment] 2017-01-19 10:26
Colorscheme generated, wallpaper set, no `wal` file :(

```
[musci@archiematti ~]$ wal -i ~/pic/0321.jpg 
colors: Generated colorscheme
colors: Set terminal colors
wallpaper: Set new wallpaper
export: Exported escape sequences
export: Exported sh colors
export: Exported scss color variables
colors: Merged colors with X env
[musci@archiematti ~]$ ls .cache/wal/
colors  colors.scss  colors.sh  schemes
[musci@archiematti ~]$ la .cache/wal/
total 24K
drwxr-xr-x 3 musci users 4.0K Jan 18 16:55 .
drwx------ 7 musci users 4.0K Jan 19 08:50 ..
-rw-r--r-- 1 musci users  441 Jan 19 10:24 colors
-rw-r--r-- 1 musci users  328 Jan 19 10:24 colors.scss
-rw-r--r-- 1 musci users  311 Jan 19 10:24 colors.sh
drwxr-xr-x 2 musci users 4.0K Jan 18 16:55 schemes
[musci@archiematti ~]$
```

**Comment by dylanaraps** [comment] 2017-01-19 10:29
I figured out the cause of the bug and it's now fixed. Thanks for testing. :)

**Closed by dylanaraps** 2017-01-19 10:29 UTC
Labels: bug
