### ISSUE TITLE
Odd text in every new terminal, and every terminal when wal is run

### ISSUE THREAD

**Issue by Delvien** [dylanaraps/wal#58] opened 2017-06-24 01:28 UTC
For example. I added the command in .bashrc to persist with new terminals, and every new (and old) terminal receives "]708;#100813" as its starting line.

Is there anyway to fix this? 

Running ubuntu 16.04, xfce + i3 with xfce4-terminal

**Comment by Delvien** [comment] 2017-06-24 03:53
Also tried it on my 17.04 install, same thing, each term starts with odd text :  ]708;#100813

**Comment by dylanaraps** [comment] 2017-06-24 06:11
Add `-t` to all of your `wal` commands.

Duplicate of https://github.com/dylanaraps/wal/issues/55 and https://github.com/dylanaraps/wal/issues/16

**Closed by dylanaraps** 2017-06-24 06:11 UTC
